### ISSUE TITLE
Add titles to every page

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#12]
Each webpage should have a title that's not the URL.

**Comment by mitchellmarshe** [comment]
Each subpage of a model has a proper title. Perhaps, you mean that we should come up with a scheme to name the URLs? If so, I think it's best to leave that idea for Phase #2 when we can make a page factory.

**Comment by cilki** [comment]
At the very least, the homepage should have a title for phase one.

**Comment by mitchellmarshe** [comment]
I believe that gets setup in AWS? Name of the homepage is gameframe.online/

**Comment by cilki** [comment]
I think someone changed it recently.

**Comment by therealsamf** [comment]
I changed it for the entire site, but I'd have to look up how to do dynamically based on the route

**Comment by mitchellmarshe** [comment]
Oh okay. Thanks for the input, Sam.
