### ISSUE TITLE
Commits and issues on about page should count all branches

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#13]
Currently, only the master branch is considered.

**Comment by therealsamf** [comment]
This is impossible to do without **a lot** of more API calls to Github, and even then I'm having trouble finding all of the commits for all branches using the API. 

Also, are we sure we want to count commits that aren't a part of what the user is currently seeing?

**Comment by cilki** [comment]
Actually this issue is somewhat obsolete now because we can just look at the `phase_*` branch instead of master.
