### ISSUE TITLE
Add Navbar Icons with Highligher

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#19]
We need an icon for games, developers, articles, and about. Then when one is on that particular page, the icon highlights up.

**Comment by atrieder** [comment]
A note on the current implementation: the categories are now highlighted when hovered over, while the icons remain highlighted at all times. This can be improved by also allowing the icons themselves to be in a dimmed state when not hovered over (such as by varying the percentage of the CSS invert property).
