### ISSUE TITLE
Global stats

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#20]
It would be nice to have a section on the homepage or on the instance grid that has stats like:
```
total games: xxxxxx
total developers: xxxxxx
total articles: xxxxxx
```

**Comment by mitchellmarshe** [comment]
I was thinking of maybe adding a popup tooltip to the navigation bar that shows these numbers respectively. Just need another endpoint that holds these counts.

**Comment by atrieder** [comment]
I think this is a good idea, since it highlights the amount of information we have organized to the user.

**Comment by mitchellmarshe** [comment]
585f1db8fcf9cdad69abb8ad7266a08b719c5a1b
Contains the commit.
