### ISSUE TITLE
CommonAssets.js is upsetting Radium

### ISSUE THREAD

**Issue by therealsamf** [cilki/gameframe.online#28]
![image](https://user-images.githubusercontent.com/11801943/37264702-efd365dc-257c-11e8-9184-a30fb956db90.png)

Using shorthand (background) as well as longhand (backgroundColor) throws tons of warnings in Radium. Apparently, this is an issue in React itself, albeit can be worked around. See https://github.com/FormidableLabs/radium/issues/95

**Comment by therealsamf** [comment]
Want to mention @atrieder as he will be the most suited to fix this while retaining what he wants the background to look like

**Comment by atrieder** [comment]
I haven't seen these warnings in the most recent commits after changing the notation, so I will close this issue now. I'll make sure to stick to one notation or the other from now on.
