### ISSUE TITLE
API needs to set `Access-Control-Allow-Origin: *` response header

### ISSUE THREAD

**Issue by therealsamf** [cilki/gameframe.online#29]
![image](https://user-images.githubusercontent.com/11801943/37264935-258b5116-257e-11e8-9bc5-b382a171dd91.png)

We need the API to set [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) response header and pushed, at least while we're developing. I have no idea if it poses a security risk in production, but because our origin, while we're developing, is `localhost`, I can't load the data into the frontend code.

**Comment by cilki** [comment]
OK I see. I'll try to fix that tonight
