### ISSUE TITLE
As a user, I want dynamic content in each instance page.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#34]
Time Estimation: 6 hours
Assumption: Flask-Restless is setup, and content in the database
Actual Time: 10 hours

**Comment by mitchellmarshe** [comment]
Each instance page is rendering at least some sort of an array of information. For instance, Game pages are rendering an array of images. Whenever the database is update, so are these images.

**Comment by therealsamf** [comment]
Each time we visit an instance page we make a request to the API for that particular instance of the model. Previously we'd been using some nontrivial caching behavior but this has proved troublesome and now each time an instance page component mounts to the DOM we send out the request to the API
