### ISSUE TITLE
As a user, I want dynamic links between instances.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#36]
Time Estimation: 6 hours
Assumption: Flask-Restless is setup, content in the database, and connections between models are established
Actual Time: 10 hours

**Comment by mitchellmarshe** [comment]
The database creates an array of http strings for each model. Then in the frontend, we get that array and dynammically populate a field of labels that are links to those models in each instance. It's pretty cool!

**Comment by therealsamf** [comment]
This proving harder to make robust than we previously thought. After navigating from page to page to page etc. it's very easy to get the site to break and not load up all of the correct links
