### ISSUE TITLE
As a user, I want dynamic content in the grid views.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#38]
Time Estimation: 12 hours
Assumption: Flask-Restless is setup, and content is in the database
Actual Time: 15 hours

**Comment by mitchellmarshe** [comment]
The major improvement made towards dynamic content in the grid models is the addition of the tooltip that renders behind each card. Each tooltip is like a snapshot of the information that the user will see when clicking on the card to link to its page instance.

**Comment by atrieder** [comment]
I agree with mitchellmarshe's description of the information that should be presented in the tooltips. The customer may be able to navigate the vast landscape of data on our website with greater ease if they don't have to enter each instance details page.

**Comment by atrieder** [comment]
With the current code, we have tooltips that include general information provided by the database.
