### ISSUE TITLE
As a user, I want to see textual country names instead of looking up the ISO 3166-1 numeric country code.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#39]
Time estimate: 5 minutes
Assumption: Know how to parse ISO country codes

**Comment by atrieder** [comment]
Reasons why this change should be implemented:
1) ISO 3166-1 numeric is the only variation of the standard that uses numbers, the alpha-2 and alpha-3 variants at least use letters.
2) Some devices do not support multitasking (such as a portable phone), so the customer may not be able to easily decipher the country codes.
3) Even if the customer has the ability to quickly decipher the country codes, having cryptic numbers on the website hurts the overall user experience.

**Comment by atrieder** [comment]
This user story is complete, since we are now using the iso-3166-1 library to parse country codes into names for both the developer cards and instance pages.

**Comment by atrieder** [comment]
Actual time: 1 hour
