### ISSUE TITLE
Windows Edge, Tooltip Rendering Issue

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#41]
When using Windows Edge, the background of the tooltip of a card isn't rendering.

**Comment by atrieder** [comment]
I have been able to reproduce this on my machine, it looks like the properties for the blur effect and those for the image size aren't working correctly.

**Comment by atrieder** [comment]
After adding the alternative blur implementation, I am now seeing correct tooltip backgrounds (though the card thumbnail sizing and non-tooltip background still aren't displayed properly).

**Comment by mitchellmarshe** [comment]
This issue no longer seems to be a problem.
