### ISSUE TITLE
FireFox, Articles cannot load due to an issue.

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#42]
Console shows this when navigating to Articles:
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
For this the Articles page isn't rendering.

**Comment by atrieder** [comment]
It isn't rendering for me in Google Chrome either

**Comment by therealsamf** [comment]
Can we check to see if this is still a bug? I'm not seeing any issues, but I don't know what specifically this bug is referring to.

**Comment by atrieder** [comment]
I think that this was when the article details pages didn't work when navigated to from the cards. It seems to work now, though I never saw the TypeError on my machine (Safari/Chrome for Mac OS).

**Comment by atrieder** [comment]
I'm closing this issue for now since the pages appear to load properly in Firefox as of the latest commit to the frontend branch.
