### ISSUE TITLE
As a user, I want a grid of images instead of text for related games, articles, etc. We will call this object the mini grid.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#44]
Time estimation: 2 hours
Assumptions: Code from the original grid can be reused

**Comment by atrieder** [comment]
As of the latest commit, the minigrid component is used on both instance detail pages and the search result page. The size of the grid can be manipulated through a percentage parameter, and the cards will resize based on a combination of the browser's width and height.

**Comment by atrieder** [comment]
Actual time: 2.5 hours
