### ISSUE TITLE
As a user, I want efficient sorting of grid pages according to any field in the database.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#45]
Time estimation: 4 hours
Assumptions: Flask-Restless's `filter` parameter will be easy to use.
Actual Time: 3.5 hours

**Comment by atrieder** [comment]
As of the last few commits, we have a working implementation of sorting via a selector field in the grid pages (to the left of the pagination component).

**Comment by mitchellmarshe** [comment]
As of now, we have most if not all ways to sort and filter content throughout the website. I think for Phase 4, the tooltip in the grid models will need to include these fields so that the user understands what's going on.
