### ISSUE TITLE
As a user, I want pagination for all model grids.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#46]
Time estimation: 8 hours
Assumptions: Our API can be utilized to control the interval of results to be returned (to return one page at a time).
Actual time: 12 hours

**Comment by atrieder** [comment]
As of the past few commits, we have a working implementation of pagination for the game, developer, and article grid pages.

**Comment by mitchellmarshe** [comment]
The pagination also scales accordingly. The buttons work within the range of the pages that are in the database. I feel like this feature is quite user friendly.
