### ISSUE TITLE
As a user, I want to search for models according to name, description, tags, and genre.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#47]
Time estimation: 8 hours
Assumptions: Flask-Restless's built in searching can do everything we need.
Actual time: 7.5 hours

We may need to create a new api for each model's searching if Flask-Restless's search parameter is insufficient.

**Comment by longhorn396** [comment]
Flask-Restless's built-in searching is indeed sufficient. 

The default ordering is Metacritic score for games and Name/Title for the other three.

**Comment by atrieder** [comment]
We also now sort developers in descending order by their number of games.

**Comment by mitchellmarshe** [comment]
The search bar works according to what the user wants. It even highlights the text for you too!
