### ISSUE TITLE
As a user, I want a button to scroll to the top of long instance pages.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#48]
Time estimation: 20 minutes
Assumptions: Scrolling to the top is a simple action

**Comment by longhorn396** [comment]
Depending on how we implement these 'mini-grids,' the instance pages could be small enough that this is no longer needed.

**Comment by mitchellmarshe** [comment]
To address our user(s), we have developed "Minigrid" and "Minicard" to display models in a nice way that doesn't make instance pages too long and of need of an button to scroll up.

**Comment by mitchellmarshe** [comment]
In regards to the actual timing of this issue, 0 minutes were spent on the button idea, however, the "Minigrid" and "Minicard" took around 8 hours of time.
