### ISSUE TITLE
About page improvements

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#49]
Here's a list of the particular issues I have with the about page:

- The pull-down effect for the cards should only apply to the bio. The commits, issues, etc, should never be hidden.
- The light gray borders and `<hr>` from phase 2 look much better than the current black borders
- The font, text size, and text colors from phase 2 look much better than the current values
- The black logo should be removed in favor of the header above the nav bar (like the homepage)
- The pull-down effect for tools should be removed
- Phase labels should be removed from tools
- Tool images should be about the same size (and smaller like phase 2)

**Comment by therealsamf** [comment]
Does the rubric for Phase 3 include improvements to the About Page?

**Comment by cilki** [comment]
No, but we can get this done before then

**Comment by cilki** [comment]
All of these issues have been addressed.
