### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#5]
Games -> Game
Developers -> Developer
Articles -> Article

Link between all besides navbar.

**Comment by cilki** [comment]
I'm not sure what this means

**Comment by therealsamf** [comment]
@mitchellmarshe I think the commit I just made fixes this issue, but I'm not exactly sure what you mean by this, so I'm leaving the issue open for now

**Comment by mitchellmarshe** [comment]
@cilki @therealsamf I mean to say that when you go to Games, then click a card, you go to the page of that instance. Within that instance, there are two links, one for its related Developer and one for its related Article. This just gives the user another way to navigate around the website without the use of the navbar.
