### ISSUE TITLE
Windows Edge, Grid Cards Not Rendering Correctly

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#52]
When using Windows Edge, all grid cards have stretched covers and some backgrounds do not show.

**Comment by atrieder** [comment]
I have been able to reproduce this issue. Additionally, the layout of the detail pages may be incorrect when viewed in Edge. It seems that the browser doesn't support the currently used combination of CSS properties (similar to how Safari used to have issues displaying the grid in earlier commits).

**Comment by mitchellmarshe** [comment]
Update: This issue is of concern to Developers.
