### ISSUE TITLE
As a user, I want a splash/homepage with a navigation bar, a carousel, and beauty.

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#53]
Time estimation: 3 hours
Assumption: Know what beauty is
Actual Time: 1 hour

We got beauty!

**Comment by longhorn396** [comment]
Do we want to add more games or do we think that four is good?

**Comment by longhorn396** [comment]
I think the navbar should also have icons.

**Comment by mitchellmarshe** [comment]
Adding on, I think the homepage should be restricted to the user's screen size. As for Phase 1, I think the homepage meets our user's request.
