### ISSUE TITLE
As a user, I want a carousel with static games, developers, or new stories.

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#54]
Time estimation: 1 hour
Assumptions: Get React and Bootstrap working
Actual time: 1 hour

We have 4 images of games within the carousel.

**Comment by longhorn396** [comment]
Do we want to add more games or do we think that four is good?

Also, do we want to link to something other than games?

**Comment by mitchellmarshe** [comment]
I believe the intent with the carousel is to show our users what is the most popular game, developer, or article in our database based on statistics. This will need to be implemented in Phase 4 as there is a lot of work ahead to get this feature popping!

In regards to Phase 1, we did have these images link to their respective page.
