### ISSUE TITLE
As a user, I need a consistent grid representation of models in the database and specific pages for each model.

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#55]
Time estimation: 6 hours
Assumption: All the tools are setup, database is constructed, and pages are populated
Actual Time: 12 hours

The models for games, developers, and articles are in the form of a grid of cards. Each card links to a specific page about it.

**Comment by atrieder** [comment]
In order for the user to effectively browse through our website's content, this functionality is important. The grid should provide enough information to assist the user in making the decision of whether to click a given model instance.

**Comment by mitchellmarshe** [comment]
The information in the grid should be easily relatable to the fields that we intent to search upon.
