### ISSUE TITLE
As a developer, I want a RESTful API that lets me query primary and secondary models along with their relationships.

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#56]
Time estimation: 3 hours
Assumption: Models are defined correctly
Actual Time: 6 hours

Our RESTful API contains those queries.

**Comment by therealsamf** [comment]
Our API is here: http://api.gameframe.online

Documentation [here](https://cilki.gitbooks.io/api/)
We used [Flask Restless](https://flask-restless.readthedocs.io/en/stable/) to create the relationships for us, all of which are documented in the link posted above
