### ISSUE TITLE
As a user I want the filter options to be in alphabetical order

### ISSUE THREAD

**Issue by SabrinaHerrero** [cilki/gameframe.online#60]
![screen shot 2018-04-09 at 4 06 28 pm](https://user-images.githubusercontent.com/15804499/38523083-142970a8-3c10-11e8-84d1-b59498c69de7.png)

For example, there are many types of platforms but I am having trouble finding PS4 especially since it is not next to the other PS platforms

**Comment by atrieder** [comment]
I think that this would improve the usability of the site, since an alphabetical ordering would make traversing the filter lists more intuitive.

**Comment by therealsamf** [comment]
This is implemented in 3a462c229738116e5a6aaee26a57b0d10c1df3a1, although it makes it harder to find the platforms most people are interested in.

**Comment by mitchellmarshe** [comment]
Estimated Time: 1 hour
Actual Time: 1 hour
