### ISSUE TITLE
As a user, I would like to see more images for each instance on the developers grid page

### ISSUE THREAD

**Issue by ccmmaa** [cilki/gameframe.online#62]
![screen shot 2018-04-09 at 4 10 05 pm](https://user-images.githubusercontent.com/14240251/38523272-92fe199c-3c10-11e8-8b1c-f0b37350286d.png)

**Comment by atrieder** [comment]
In commit 74ccb449ef149b7d283345a377c8d8d6ef8311e4, we now display a 'No Image' placeholder for cards that do not have an accessible cover image:

![INTERWEB](https://user-images.githubusercontent.com/21695410/38951898-94eb4c1a-430f-11e8-970a-09d2ffc498f4.png)

Though these instances don't have their own covers, it would still be useful to retain them in our database. That way, instances from other models can still reference them. I think that the implementation shown in the above image may be a sufficient solution to this user story.

**Comment by mitchellmarshe** [comment]
Estimated Time: 20 min
Actual Time: 20 min
