### ISSUE TITLE
As a user, I'd like to see the dots on the carousel on all the slides. Maybe add a tinted background shadow, or a more contrasting color dots.

### ISSUE THREAD

**Issue by ChiaHuaLu** [cilki/gameframe.online#64]
<img width="960" alt="gameframe" src="https://user-images.githubusercontent.com/15913503/38523564-8698c23c-3c11-11e8-82e6-587271cc9d18.png">
On the rocket league slide, the dots are near impossible to see.

**Comment by atrieder** [comment]
In commit 8bfd2c934927d08d2d961568e526c06032605830, I added a line to the bootstrap carousel CSS to color the controls the inverse of whatever is behind them. This results in the controls changing to a darker color when the carousel image is bright, and vice versa.
![untitled](https://user-images.githubusercontent.com/21695410/38592530-3104911a-3d02-11e8-99b1-95e47b3eeb2a.png)

**Comment by mitchellmarshe** [comment]
Estimated Time: 20 min
Actual Time: 5 min
