### ISSUE TITLE
As a user I want to be able to see see the union of filters and not just the intersection

### ISSUE THREAD

**Issue by SabrinaHerrero** [cilki/gameframe.online#65]
![screen shot 2018-04-09 at 4 12 31 pm](https://user-images.githubusercontent.com/15804499/38523386-ed656ffc-3c10-11e8-8128-e8a13a30d273.png)
For example, if I only have two game platforms available to me, I am looking for the games that are available on linux and I'm interested in seeing games that are available on TI-99. 

Currently getting the intersection is also a nice thing to have like which games are available for both. I want this more as an additional function. Though I am not sure how you would differentiate these on your site.

**Comment by therealsamf** [comment]
Used [react-bootstrap-toggle](https://www.npmjs.com/package/react-bootstrap-toggle) to allow the user to choose whether to use AND/OR (short for intersection/union) in the way their filters are applied

**Comment by mitchellmarshe** [comment]
Estimated Time: 1 hour
Actual Time: 2 hour
