### ISSUE TITLE
As a user, I'd like to see text not being cut off, and slight space between text and its container's edge

### ISSUE THREAD

**Issue by ChiaHuaLu** [cilki/gameframe.online#68]
All the text should be visible, and preferably with a bit of padding under it so that it doesn't feel claustrophobic.
<img width="960" alt="gameframe" src="https://user-images.githubusercontent.com/15913503/38524162-4e91efd8-3c13-11e8-9a2f-5ee51c20434e.png">

**Comment by mitchellmarshe** [comment]
To address this concern of yours, ChiaHuaLu, I will look into how I can scale these card elements according to the screen so that text is shown appropriately. I estimate that this story will take me 1 hour.

**Comment by mitchellmarshe** [comment]
I have now improved our about page to scale as best as it can for all screen sizes. I will admit the tablet form isn't so nice, but I couldn't use media query along with Radium effects. This took me about an hour to get done as estimated.
