### ISSUE TITLE
As a user it would be nice if I could click the genre in a game instance and be redirected to games of the same genre

### ISSUE THREAD

**Issue by SabrinaHerrero** [cilki/gameframe.online#69]
For instance when I click the genre I want to be taken to the main game page with the genre filled in as a filter

![screen shot 2018-04-09 at 4 29 04 pm](https://user-images.githubusercontent.com/15804499/38524216-7f6ed3d2-3c13-11e8-8100-8567e3bdfdfa.png)
![screen shot 2018-04-09 at 4 29 17 pm](https://user-images.githubusercontent.com/15804499/38524221-820d81f6-3c13-11e8-979d-ffae62044f08.png)

**Comment by longhorn396** [comment]
Since we do not have URL supported filtering, we decided to make them link to the search page instead. It also works for the Platform tags as well. 

Estimated time: 1 hour
Actual time: 20 minutes
