### ISSUE TITLE
As a user, I would like it if the tags didn't get cut off

### ISSUE THREAD

**Issue by ccmmaa** [cilki/gameframe.online#70]
![screen shot 2018-04-09 at 4 30 14 pm](https://user-images.githubusercontent.com/14240251/38524198-6d87b436-3c13-11e8-8f00-28f11a9c07f5.png)
Specifically the instance on the top right.

**Comment by mitchellmarshe** [comment]
To address your concerns, ccmmaa, I've put genres and platforms into a carousel in order to avoid this cutoff. In addition, there are now all of the genres and platforms instead of just 3. You can see this fix in issue #71 as well as the time of completion.
