### ISSUE TITLE
Requesting More From api/grid/game

### ISSUE THREAD

**Issue by mitchellmarshe** [cilki/gameframe.online#73]
I request the following fields: vindex, metacritic, and esrb.

**Comment by therealsamf** [comment]
@cilki Maybe just attach all attributes by default that aren't linking to another model? Seems like those are the biggest slowdowns in the requests

**Comment by mitchellmarshe** [comment]
In addition, I'd like the links for steam and igdb.

**Comment by mitchellmarshe** [comment]
All requests are fulfilled.
