### ISSUE TITLE
Improve current Steam players appearance

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#76]
![2018-04-13-182329_3840x1080_scrot](https://user-images.githubusercontent.com/10459406/38761389-dc14d8a2-3f47-11e8-9362-b9f323d9c63e.png)

1. Change the text to "# players in-game"
2. Let's add the Steam logo similar to Metacritic
3. Link it to `http://steamcharts.com/app/<app id>`

**Comment by atrieder** [comment]
Since the steam player count has been redesigned and links to steamcharts.com in commit 32110a038295f914e63762957106e03317a8af4f, I think that this issue has been successfully completed.
