### ISSUE TITLE
Disable scrollbars for minigrid title text

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#77]
![2018-04-13-183311_3840x1080_scrot](https://user-images.githubusercontent.com/10459406/38761529-4a6f4a3e-3f49-11e8-8c92-7a9d6ea3a4b8.png)
This may just be my GTK theme interfering, but it would be great if no scrollbars appeared for the titles. If it can't be fixed, don't worry about it because the title expansion is still awesome.

**Comment by atrieder** [comment]
With commit ca62d09406acb574073000ccd1c8751a53e0a605, I am no longer seeing scrollbars on the minicards when using Windows.
