### ISSUE TITLE
Navigating from Developer to Game brings you to the middle of the page

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#79]
Clicking on a game from a developer's minigrid takes you to the middle of the game's instance page.

Steps to reproduce:
- Go to a Developer's instance page
- Go to one of their games

Expected behaviour:
- The user should be brought to the top of the page

This doesn't seem to happen from Articles->Games or Articles->Developers

**Comment by mitchellmarshe** [comment]
9b30145eee4562865e23271c93b66a8e58024bb3
This commit shows the fix.
