### ISSUE TITLE
Add graph to developer instance page

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#82]
Similar to games, we can chart the number of games a developer has released by year next to the Google trends graph.

**Comment by cilki** [comment]
Maybe we could make this graph a scatter plot with years on the x axis and months on the y axis. Each game release would then be a particular dot on the graph.

The x axis would range from the foundation year to 2018 and the y axis would range from Jan to Dec skipping every few months.

**Comment by therealsamf** [comment]
This probably isn't going to get done before Thursday night

**Comment by cilki** [comment]
;(
