### ISSUE TITLE
Add description text to developer instance page

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#84]
Some developers have descriptions in the `description` field which should be rendered on the instance page similar to the game synopsis.

**Comment by longhorn396** [comment]
These are displayed when they exist. @atrieder Could you make it look pretty?

**Comment by atrieder** [comment]
I pushed 212fcd303302df92e6a87284e4d45b8c6c880c93 earlier today, which styles the descriptions to appear like the game pages:

![seeegaa](https://user-images.githubusercontent.com/21695410/38957565-9c22a3a0-4320-11e8-8212-5f649c4d95fe.png)

Does the above look ok?

**Comment by longhorn396** [comment]
It looks great
