### ISSUE TITLE
Dynamic Titles

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#88]
We should make the webpage titles more specific.
For the main pages, something like: `GameFrame - About`, `GameFrame - Games`, ...
The instance pages could be `GameFrame - <name of instance>`

**Comment by mitchellmarshe** [comment]
The problem with this is that some instance titles are rather long. I believe if people were to start indexing this website, the numbers are easy to do so. Also, I believe other developers would like the relationship between the site and the API.

**Comment by atrieder** [comment]
All pages now have dynamic titles as of commit 030f1b7a2b28d5018d7c3de9049723f411702fb3. I used the react-helmet library to change the <title> element on each page.
